"""
tools/pdf_blob_tool.py
────────────────────────────────────────────────────────────────────────────
Generates a styled travel PDF from any content and saves it to
Azure Blob Storage. Called automatically whenever the email tool is used.

Workflow:
  User: "email me the Bali itinerary to alice@example.com"
    → Agent calls send_email(...)        ← sends the email
    → Agent calls generate_and_save_pdf(...) ← saves PDF to blob
    → Agent confirms both actions to user

PDF library: reportlab (pure Python, no system dependencies)
  pip install reportlab

Azure Blob: free tier — 5 GB storage
  Connection string: portal.azure.com → Storage account → Access keys
────────────────────────────────────────────────────────────────────────────
"""

import os
import re
import io
from datetime import datetime
from langchain_core.tools import tool


# ─────────────────────────────────────────────────────────────────────────────
# Azure Blob helper
# ─────────────────────────────────────────────────────────────────────────────

def _upload_pdf_to_blob(pdf_bytes: bytes, blob_name: str) -> str:
    """Upload PDF bytes to Azure Blob Storage and return the public URL."""
    conn_str  = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
    container = os.getenv("AZURE_STORAGE_CONTAINER_NAME", "travel-images")

    if not conn_str or not conn_str.startswith("DefaultEndpoints"):
        raise EnvironmentError(
            "AZURE_STORAGE_CONNECTION_STRING not set in .env\n"
            "Get it: portal.azure.com → Storage account → Access keys → Connection string"
        )

    try:
        from azure.storage.blob import BlobServiceClient, ContentSettings
    except ImportError:
        raise ImportError("Run: pip install azure-storage-blob")

    svc    = BlobServiceClient.from_connection_string(conn_str)
    client = svc.get_blob_client(container=container, blob=blob_name)
    client.upload_blob(
        pdf_bytes,
        blob_type     = "BlockBlob",
        content_settings = ContentSettings(content_type="application/pdf"),
        overwrite     = True,
    )
    return client.url


def _sanitize(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "_", text.strip().lower())


# ─────────────────────────────────────────────────────────────────────────────
# PDF builder using reportlab
# ─────────────────────────────────────────────────────────────────────────────

def _build_pdf(subject: str, body: str, recipient: str) -> bytes:
    """
    Build a styled travel-themed PDF using reportlab.
    Returns raw PDF bytes.

    Layout:
      • Header bar  — blue gradient with ✈️ Aria Travel Agent branding
      • Meta block  — To, Date, Subject
      • Divider
      • Body text   — auto-wrapped, preserves line breaks and bullet points
      • Footer      — generated by Aria / Azure OpenAI
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer,
            HRFlowable, Table, TableStyle,
        )
    except ImportError:
        raise ImportError("Run: pip install reportlab")

    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize     = A4,
        leftMargin   = 20 * mm,
        rightMargin  = 20 * mm,
        topMargin    = 15 * mm,
        bottomMargin = 20 * mm,
        title        = subject,
        author       = "Aria AI Travel Agent",
    )

    # ── Colour palette ────────────────────────────────────────────────────
    DARK_BLUE   = colors.HexColor("#0d47a1")
    MID_BLUE    = colors.HexColor("#1565c0")
    LIGHT_BLUE  = colors.HexColor("#e3f2fd")
    ACCENT      = colors.HexColor("#42a5f5")
    TEXT_DARK   = colors.HexColor("#1a237e")
    TEXT_BODY   = colors.HexColor("#212121")
    TEXT_MUTED  = colors.HexColor("#757575")

    # ── Styles ─────────────────────────────────────────────────────────────
    styles = getSampleStyleSheet()

    header_style = ParagraphStyle(
        "Header",
        fontSize  = 22,
        textColor = colors.white,
        fontName  = "Helvetica-Bold",
        alignment = TA_CENTER,
        spaceAfter = 2,
    )
    sub_header_style = ParagraphStyle(
        "SubHeader",
        fontSize  = 9,
        textColor = colors.HexColor("#bbdefb"),
        fontName  = "Helvetica",
        alignment = TA_CENTER,
    )
    subject_style = ParagraphStyle(
        "Subject",
        fontSize   = 13,
        textColor  = DARK_BLUE,
        fontName   = "Helvetica-Bold",
        spaceAfter = 4,
    )
    meta_label_style = ParagraphStyle(
        "MetaLabel",
        fontSize  = 8,
        textColor = TEXT_MUTED,
        fontName  = "Helvetica-Bold",
    )
    meta_value_style = ParagraphStyle(
        "MetaValue",
        fontSize  = 9,
        textColor = TEXT_DARK,
        fontName  = "Helvetica",
    )
    body_style = ParagraphStyle(
        "Body",
        fontSize    = 10,
        textColor   = TEXT_BODY,
        fontName    = "Helvetica",
        leading     = 16,
        spaceAfter  = 4,
        leftIndent  = 0,
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        fontSize    = 10,
        textColor   = TEXT_BODY,
        fontName    = "Helvetica",
        leading     = 15,
        leftIndent  = 12,
        spaceAfter  = 2,
    )
    heading_style = ParagraphStyle(
        "Heading",
        fontSize    = 11,
        textColor   = MID_BLUE,
        fontName    = "Helvetica-Bold",
        spaceBefore = 8,
        spaceAfter  = 3,
    )
    footer_style = ParagraphStyle(
        "Footer",
        fontSize  = 8,
        textColor = TEXT_MUTED,
        fontName  = "Helvetica-Oblique",
        alignment = TA_CENTER,
    )

    story = []
    W = A4[0] - 40 * mm   # usable width

    # ── Header banner ──────────────────────────────────────────────────────
    header_table = Table(
        [[Paragraph("✈️  Aria Travel Agent", header_style)],
         [Paragraph("AI-Powered Travel Planning  •  Azure OpenAI + LangGraph", sub_header_style)]],
        colWidths=[W],
    )
    header_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, -1), MID_BLUE),
        ("TOPPADDING",  (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 14),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("ROUNDEDCORNERS", [6]),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 6 * mm))

    # ── Meta block ─────────────────────────────────────────────────────────
    now       = datetime.now().strftime("%B %d, %Y  %I:%M %p")
    meta_data = [
        ["TO",      recipient],
        ["DATE",    now],
        ["SUBJECT", subject],
    ]
    meta_table = Table(
        [[Paragraph(label, meta_label_style), Paragraph(value, meta_value_style)]
         for label, value in meta_data],
        colWidths=[18 * mm, W - 18 * mm],
    )
    meta_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), LIGHT_BLUE),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LINEBELOW",     (0, 0), (-1, -2), 0.3, colors.HexColor("#90caf9")),
        ("ROUNDEDCORNERS", [4]),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 5 * mm))
    story.append(HRFlowable(width=W, thickness=1.5, color=ACCENT, spaceAfter=5 * mm))

    # ── Body ───────────────────────────────────────────────────────────────
    # Parse body text — detect headings (Day X, ALL CAPS lines), bullets, plain text
    for line in body.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 3 * mm))
            continue

        # Detect section headings: "Day 1", "## Heading", "HEADING:"
        if (
            re.match(r"^(Day\s+\d+|#{1,3}\s+.+|[A-Z][A-Z\s]{3,}:?)$", stripped)
            or stripped.endswith(":") and len(stripped) < 50 and stripped[0].isupper()
        ):
            # Escape XML special chars
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, heading_style))

        # Bullet points: lines starting with •, *, -, ✅, ✈️, 🌤 etc.
        elif re.match(r"^[•\-\*✅✈️🌤💱🗺🌍📅💡📧🔍📦🔗📏⚠️❌📸🖼📂📁]", stripped):
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, bullet_style))

        # Numbered list: "1. ...", "  1. ..."
        elif re.match(r"^\d+[\.\)]\s+", stripped):
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, bullet_style))

        # Normal paragraph
        else:
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, body_style))

    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width=W, thickness=0.5, color=colors.HexColor("#bbdefb"), spaceAfter=3 * mm))

    # ── Footer ─────────────────────────────────────────────────────────────
    story.append(Paragraph(
        f"Generated by Aria AI Travel Agent  •  Powered by Azure OpenAI &amp; LangGraph  •  {now}",
        footer_style,
    ))
    story.append(Paragraph(
        "This document was automatically generated from your travel query.",
        footer_style,
    ))

    doc.build(story)
    return buffer.getvalue()


# ─────────────────────────────────────────────────────────────────────────────
# LangChain tool
# ─────────────────────────────────────────────────────────────────────────────

@tool
def generate_and_save_pdf(subject: str, body: str, recipient: str) -> str:
    """
    Generate a styled travel PDF from the given content and save it to
    Azure Blob Storage. Call this IMMEDIATELY AFTER send_email succeeds.

    The PDF is a permanent record of what was emailed — same subject and
    body as the email, saved as a PDF in blob storage for future reference.

    Args:
        subject  : Email subject / PDF title (e.g. "5-Day Bali Itinerary")
        body     : Full plain-text content that was emailed to the user.
                   Include all details — weather, itinerary, tips, etc.
        recipient: Email address the content was sent to (used in PDF header)

    Returns:
        Confirmation with the blob URL where the PDF is stored,
        or a specific error message if saving failed.
    """
    conn_str = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
    if not conn_str or not conn_str.startswith("DefaultEndpoints"):
        return (
            "⚠️ PDF not saved — Azure Blob Storage not configured.\n"
            "Add AZURE_STORAGE_CONNECTION_STRING to .env to enable PDF archiving."
        )

    try:
        # Build PDF
        pdf_bytes = _build_pdf(subject, body, recipient)

        # Blob path: pdfs/2024-03-16/bali_itinerary_alice_example_com.pdf
        date_slug      = datetime.utcnow().strftime("%Y-%m-%d")
        subject_slug   = _sanitize(subject)[:50]
        recipient_slug = _sanitize(recipient)[:30]
        blob_name      = f"pdfs/{date_slug}/{subject_slug}_{recipient_slug}.pdf"

        blob_url = _upload_pdf_to_blob(pdf_bytes, blob_name)
        size_kb  = round(len(pdf_bytes) / 1024, 1)

        return (
            f"📄 PDF saved to Azure Blob Storage!\n"
            f"  📋 Title    : {subject}\n"
            f"  📧 For      : {recipient}\n"
            f"  📦 Blob     : {blob_name}\n"
            f"  🔗 URL      : {blob_url}\n"
            f"  📏 Size     : {size_kb} KB\n"
            f"  📅 Saved on : {datetime.utcnow().strftime('%B %d, %Y %H:%M UTC')}\n\n"
            f"💡 View all saved PDFs in Azure Portal:\n"
            f"   Storage account → Containers → "
            f"{os.getenv('AZURE_STORAGE_CONTAINER_NAME', 'travel-images')} → pdfs/"
        )

    except ImportError as e:
        return (
            f"⚠️ PDF generation requires reportlab.\n"
            f"Run: pip install reportlab\n"
            f"Error: {e}"
        )
    except EnvironmentError as e:
        return f"⚠️ Blob Storage error: {e}"
    except Exception as e:
        return f"⚠️ PDF save failed: {type(e).__name__}: {e}"
